import type { Metadata } from "next";;
import "./globals.css";
import ReduxProvider from "@/redux/StoreProivder";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Vivek Kumar | Portfoilio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <main>
          <ReduxProvider>
            <Header />
            {children}
            <Footer />
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
